set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_bready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/interrupt]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_arready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_arvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_awvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_bvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_rlast]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_rready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_rvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_wlast]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_wready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_arvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_awready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_wready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_wvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/m_axi_wvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_arready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_awready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_awvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_bready]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_bvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_rvalid]
set_property MARK_DEBUG true [get_nets riscv_i/IO/SD/s_axi_rready]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[19]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[19]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rresp[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rresp[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_bresp[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[9]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[1]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awlen[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_bresp[0]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[6]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[30]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[14]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[22]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[20]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_arlen[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[5]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_araddr[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[29]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[13]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_rdata[21]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/m_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_araddr[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[11]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {riscv_i/IO/SD/s_axi_rdata[19]}]
set_property MARK_DEBUG false [get_nets riscv_i/IO/SD/async_resetn]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list riscv_i/clk_wiz_0/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {riscv_i/IO/SD/m_axi_arlen[0]} {riscv_i/IO/SD/m_axi_arlen[1]} {riscv_i/IO/SD/m_axi_arlen[2]} {riscv_i/IO/SD/m_axi_arlen[3]} {riscv_i/IO/SD/m_axi_arlen[4]} {riscv_i/IO/SD/m_axi_arlen[5]} {riscv_i/IO/SD/m_axi_arlen[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {riscv_i/IO/SD/s_axi_rdata[0]} {riscv_i/IO/SD/s_axi_rdata[1]} {riscv_i/IO/SD/s_axi_rdata[2]} {riscv_i/IO/SD/s_axi_rdata[3]} {riscv_i/IO/SD/s_axi_rdata[4]} {riscv_i/IO/SD/s_axi_rdata[5]} {riscv_i/IO/SD/s_axi_rdata[6]} {riscv_i/IO/SD/s_axi_rdata[7]} {riscv_i/IO/SD/s_axi_rdata[8]} {riscv_i/IO/SD/s_axi_rdata[9]} {riscv_i/IO/SD/s_axi_rdata[10]} {riscv_i/IO/SD/s_axi_rdata[11]} {riscv_i/IO/SD/s_axi_rdata[12]} {riscv_i/IO/SD/s_axi_rdata[13]} {riscv_i/IO/SD/s_axi_rdata[14]} {riscv_i/IO/SD/s_axi_rdata[15]} {riscv_i/IO/SD/s_axi_rdata[16]} {riscv_i/IO/SD/s_axi_rdata[17]} {riscv_i/IO/SD/s_axi_rdata[18]} {riscv_i/IO/SD/s_axi_rdata[19]} {riscv_i/IO/SD/s_axi_rdata[20]} {riscv_i/IO/SD/s_axi_rdata[21]} {riscv_i/IO/SD/s_axi_rdata[22]} {riscv_i/IO/SD/s_axi_rdata[23]} {riscv_i/IO/SD/s_axi_rdata[24]} {riscv_i/IO/SD/s_axi_rdata[25]} {riscv_i/IO/SD/s_axi_rdata[26]} {riscv_i/IO/SD/s_axi_rdata[27]} {riscv_i/IO/SD/s_axi_rdata[28]} {riscv_i/IO/SD/s_axi_rdata[29]} {riscv_i/IO/SD/s_axi_rdata[30]} {riscv_i/IO/SD/s_axi_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {riscv_i/IO/SD/s_axi_araddr[0]} {riscv_i/IO/SD/s_axi_araddr[1]} {riscv_i/IO/SD/s_axi_araddr[2]} {riscv_i/IO/SD/s_axi_araddr[3]} {riscv_i/IO/SD/s_axi_araddr[4]} {riscv_i/IO/SD/s_axi_araddr[5]} {riscv_i/IO/SD/s_axi_araddr[6]} {riscv_i/IO/SD/s_axi_araddr[7]} {riscv_i/IO/SD/s_axi_araddr[8]} {riscv_i/IO/SD/s_axi_araddr[9]} {riscv_i/IO/SD/s_axi_araddr[10]} {riscv_i/IO/SD/s_axi_araddr[11]} {riscv_i/IO/SD/s_axi_araddr[12]} {riscv_i/IO/SD/s_axi_araddr[13]} {riscv_i/IO/SD/s_axi_araddr[14]} {riscv_i/IO/SD/s_axi_araddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {riscv_i/IO/SD/s_axi_wdata[0]} {riscv_i/IO/SD/s_axi_wdata[1]} {riscv_i/IO/SD/s_axi_wdata[2]} {riscv_i/IO/SD/s_axi_wdata[3]} {riscv_i/IO/SD/s_axi_wdata[4]} {riscv_i/IO/SD/s_axi_wdata[5]} {riscv_i/IO/SD/s_axi_wdata[6]} {riscv_i/IO/SD/s_axi_wdata[7]} {riscv_i/IO/SD/s_axi_wdata[8]} {riscv_i/IO/SD/s_axi_wdata[9]} {riscv_i/IO/SD/s_axi_wdata[10]} {riscv_i/IO/SD/s_axi_wdata[11]} {riscv_i/IO/SD/s_axi_wdata[12]} {riscv_i/IO/SD/s_axi_wdata[13]} {riscv_i/IO/SD/s_axi_wdata[14]} {riscv_i/IO/SD/s_axi_wdata[15]} {riscv_i/IO/SD/s_axi_wdata[16]} {riscv_i/IO/SD/s_axi_wdata[17]} {riscv_i/IO/SD/s_axi_wdata[18]} {riscv_i/IO/SD/s_axi_wdata[19]} {riscv_i/IO/SD/s_axi_wdata[20]} {riscv_i/IO/SD/s_axi_wdata[21]} {riscv_i/IO/SD/s_axi_wdata[22]} {riscv_i/IO/SD/s_axi_wdata[23]} {riscv_i/IO/SD/s_axi_wdata[24]} {riscv_i/IO/SD/s_axi_wdata[25]} {riscv_i/IO/SD/s_axi_wdata[26]} {riscv_i/IO/SD/s_axi_wdata[27]} {riscv_i/IO/SD/s_axi_wdata[28]} {riscv_i/IO/SD/s_axi_wdata[29]} {riscv_i/IO/SD/s_axi_wdata[30]} {riscv_i/IO/SD/s_axi_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {riscv_i/IO/SD/s_axi_awaddr[0]} {riscv_i/IO/SD/s_axi_awaddr[1]} {riscv_i/IO/SD/s_axi_awaddr[2]} {riscv_i/IO/SD/s_axi_awaddr[3]} {riscv_i/IO/SD/s_axi_awaddr[4]} {riscv_i/IO/SD/s_axi_awaddr[5]} {riscv_i/IO/SD/s_axi_awaddr[6]} {riscv_i/IO/SD/s_axi_awaddr[7]} {riscv_i/IO/SD/s_axi_awaddr[8]} {riscv_i/IO/SD/s_axi_awaddr[9]} {riscv_i/IO/SD/s_axi_awaddr[10]} {riscv_i/IO/SD/s_axi_awaddr[11]} {riscv_i/IO/SD/s_axi_awaddr[12]} {riscv_i/IO/SD/s_axi_awaddr[13]} {riscv_i/IO/SD/s_axi_awaddr[14]} {riscv_i/IO/SD/s_axi_awaddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {riscv_i/IO/SD/m_axi_rresp[0]} {riscv_i/IO/SD/m_axi_rresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 7 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {riscv_i/IO/SD/m_axi_awlen[0]} {riscv_i/IO/SD/m_axi_awlen[1]} {riscv_i/IO/SD/m_axi_awlen[2]} {riscv_i/IO/SD/m_axi_awlen[3]} {riscv_i/IO/SD/m_axi_awlen[4]} {riscv_i/IO/SD/m_axi_awlen[5]} {riscv_i/IO/SD/m_axi_awlen[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {riscv_i/IO/SD/m_axi_bresp[0]} {riscv_i/IO/SD/m_axi_bresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {riscv_i/IO/SD/m_axi_rdata[0]} {riscv_i/IO/SD/m_axi_rdata[1]} {riscv_i/IO/SD/m_axi_rdata[2]} {riscv_i/IO/SD/m_axi_rdata[3]} {riscv_i/IO/SD/m_axi_rdata[4]} {riscv_i/IO/SD/m_axi_rdata[5]} {riscv_i/IO/SD/m_axi_rdata[6]} {riscv_i/IO/SD/m_axi_rdata[7]} {riscv_i/IO/SD/m_axi_rdata[8]} {riscv_i/IO/SD/m_axi_rdata[9]} {riscv_i/IO/SD/m_axi_rdata[10]} {riscv_i/IO/SD/m_axi_rdata[11]} {riscv_i/IO/SD/m_axi_rdata[12]} {riscv_i/IO/SD/m_axi_rdata[13]} {riscv_i/IO/SD/m_axi_rdata[14]} {riscv_i/IO/SD/m_axi_rdata[15]} {riscv_i/IO/SD/m_axi_rdata[16]} {riscv_i/IO/SD/m_axi_rdata[17]} {riscv_i/IO/SD/m_axi_rdata[18]} {riscv_i/IO/SD/m_axi_rdata[19]} {riscv_i/IO/SD/m_axi_rdata[20]} {riscv_i/IO/SD/m_axi_rdata[21]} {riscv_i/IO/SD/m_axi_rdata[22]} {riscv_i/IO/SD/m_axi_rdata[23]} {riscv_i/IO/SD/m_axi_rdata[24]} {riscv_i/IO/SD/m_axi_rdata[25]} {riscv_i/IO/SD/m_axi_rdata[26]} {riscv_i/IO/SD/m_axi_rdata[27]} {riscv_i/IO/SD/m_axi_rdata[28]} {riscv_i/IO/SD/m_axi_rdata[29]} {riscv_i/IO/SD/m_axi_rdata[30]} {riscv_i/IO/SD/m_axi_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {riscv_i/IO/SD/m_axi_wdata[0]} {riscv_i/IO/SD/m_axi_wdata[1]} {riscv_i/IO/SD/m_axi_wdata[2]} {riscv_i/IO/SD/m_axi_wdata[3]} {riscv_i/IO/SD/m_axi_wdata[4]} {riscv_i/IO/SD/m_axi_wdata[5]} {riscv_i/IO/SD/m_axi_wdata[6]} {riscv_i/IO/SD/m_axi_wdata[7]} {riscv_i/IO/SD/m_axi_wdata[8]} {riscv_i/IO/SD/m_axi_wdata[9]} {riscv_i/IO/SD/m_axi_wdata[10]} {riscv_i/IO/SD/m_axi_wdata[11]} {riscv_i/IO/SD/m_axi_wdata[12]} {riscv_i/IO/SD/m_axi_wdata[13]} {riscv_i/IO/SD/m_axi_wdata[14]} {riscv_i/IO/SD/m_axi_wdata[15]} {riscv_i/IO/SD/m_axi_wdata[16]} {riscv_i/IO/SD/m_axi_wdata[17]} {riscv_i/IO/SD/m_axi_wdata[18]} {riscv_i/IO/SD/m_axi_wdata[19]} {riscv_i/IO/SD/m_axi_wdata[20]} {riscv_i/IO/SD/m_axi_wdata[21]} {riscv_i/IO/SD/m_axi_wdata[22]} {riscv_i/IO/SD/m_axi_wdata[23]} {riscv_i/IO/SD/m_axi_wdata[24]} {riscv_i/IO/SD/m_axi_wdata[25]} {riscv_i/IO/SD/m_axi_wdata[26]} {riscv_i/IO/SD/m_axi_wdata[27]} {riscv_i/IO/SD/m_axi_wdata[28]} {riscv_i/IO/SD/m_axi_wdata[29]} {riscv_i/IO/SD/m_axi_wdata[30]} {riscv_i/IO/SD/m_axi_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 30 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {riscv_i/IO/SD/m_axi_awaddr[2]} {riscv_i/IO/SD/m_axi_awaddr[3]} {riscv_i/IO/SD/m_axi_awaddr[4]} {riscv_i/IO/SD/m_axi_awaddr[5]} {riscv_i/IO/SD/m_axi_awaddr[6]} {riscv_i/IO/SD/m_axi_awaddr[7]} {riscv_i/IO/SD/m_axi_awaddr[8]} {riscv_i/IO/SD/m_axi_awaddr[9]} {riscv_i/IO/SD/m_axi_awaddr[10]} {riscv_i/IO/SD/m_axi_awaddr[11]} {riscv_i/IO/SD/m_axi_awaddr[12]} {riscv_i/IO/SD/m_axi_awaddr[13]} {riscv_i/IO/SD/m_axi_awaddr[14]} {riscv_i/IO/SD/m_axi_awaddr[15]} {riscv_i/IO/SD/m_axi_awaddr[16]} {riscv_i/IO/SD/m_axi_awaddr[17]} {riscv_i/IO/SD/m_axi_awaddr[18]} {riscv_i/IO/SD/m_axi_awaddr[19]} {riscv_i/IO/SD/m_axi_awaddr[20]} {riscv_i/IO/SD/m_axi_awaddr[21]} {riscv_i/IO/SD/m_axi_awaddr[22]} {riscv_i/IO/SD/m_axi_awaddr[23]} {riscv_i/IO/SD/m_axi_awaddr[24]} {riscv_i/IO/SD/m_axi_awaddr[25]} {riscv_i/IO/SD/m_axi_awaddr[26]} {riscv_i/IO/SD/m_axi_awaddr[27]} {riscv_i/IO/SD/m_axi_awaddr[28]} {riscv_i/IO/SD/m_axi_awaddr[29]} {riscv_i/IO/SD/m_axi_awaddr[30]} {riscv_i/IO/SD/m_axi_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 30 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {riscv_i/IO/SD/m_axi_araddr[2]} {riscv_i/IO/SD/m_axi_araddr[3]} {riscv_i/IO/SD/m_axi_araddr[4]} {riscv_i/IO/SD/m_axi_araddr[5]} {riscv_i/IO/SD/m_axi_araddr[6]} {riscv_i/IO/SD/m_axi_araddr[7]} {riscv_i/IO/SD/m_axi_araddr[8]} {riscv_i/IO/SD/m_axi_araddr[9]} {riscv_i/IO/SD/m_axi_araddr[10]} {riscv_i/IO/SD/m_axi_araddr[11]} {riscv_i/IO/SD/m_axi_araddr[12]} {riscv_i/IO/SD/m_axi_araddr[13]} {riscv_i/IO/SD/m_axi_araddr[14]} {riscv_i/IO/SD/m_axi_araddr[15]} {riscv_i/IO/SD/m_axi_araddr[16]} {riscv_i/IO/SD/m_axi_araddr[17]} {riscv_i/IO/SD/m_axi_araddr[18]} {riscv_i/IO/SD/m_axi_araddr[19]} {riscv_i/IO/SD/m_axi_araddr[20]} {riscv_i/IO/SD/m_axi_araddr[21]} {riscv_i/IO/SD/m_axi_araddr[22]} {riscv_i/IO/SD/m_axi_araddr[23]} {riscv_i/IO/SD/m_axi_araddr[24]} {riscv_i/IO/SD/m_axi_araddr[25]} {riscv_i/IO/SD/m_axi_araddr[26]} {riscv_i/IO/SD/m_axi_araddr[27]} {riscv_i/IO/SD/m_axi_araddr[28]} {riscv_i/IO/SD/m_axi_araddr[29]} {riscv_i/IO/SD/m_axi_araddr[30]} {riscv_i/IO/SD/m_axi_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list riscv_i/IO/SD/interrupt]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list riscv_i/IO/SD/m_axi_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list riscv_i/IO/SD/m_axi_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list riscv_i/IO/SD/m_axi_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list riscv_i/IO/SD/m_axi_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list riscv_i/IO/SD/m_axi_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list riscv_i/IO/SD/m_axi_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list riscv_i/IO/SD/m_axi_rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list riscv_i/IO/SD/m_axi_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list riscv_i/IO/SD/m_axi_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list riscv_i/IO/SD/m_axi_wlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list riscv_i/IO/SD/m_axi_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list riscv_i/IO/SD/m_axi_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list riscv_i/IO/SD/s_axi_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list riscv_i/IO/SD/s_axi_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list riscv_i/IO/SD/s_axi_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list riscv_i/IO/SD/s_axi_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list riscv_i/IO/SD/s_axi_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list riscv_i/IO/SD/s_axi_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list riscv_i/IO/SD/s_axi_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list riscv_i/IO/SD/s_axi_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list riscv_i/IO/SD/s_axi_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list riscv_i/IO/SD/s_axi_wvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out3]
